### ISSUE TITLE
Module not found in NPM

### ISSUE THREAD

**Issue by pfftdammitchris** [jessestuart/gatsby-source-s3-image#1]
Hello there, great package!

However this cannot be installed from the NPM CLI:

![image](https://user-images.githubusercontent.com/20717348/39095921-2c97d156-45fd-11e8-9610-f6fee69e1456.png)

**Comment by jessestuart** [comment]
Hiya @pfftdammitchris,
Thanks for checking it out, and for pointing out the issue! The package name is actually `gatsby-source-s3-image`, with "image" spelled out — apologies for the misleading documentation in the README. I'd originally used the name `gatsby-source-s3-img`, but that tripped up NPM's "spam detection" for some reason (and apparently I'm not the [only](https://github.com/npm/registry/issues/304) [one](https://stackoverflow.com/questions/48668389/npm-publish-failed-with-package-name-triggered-spam-detection) seeing false positives). 

I've just updated the docs so everything references the correct NPM package. Let me know if you have any other questions or issues!
