### ISSUE TITLE
Error: Unable to find plugin "gatsby-source-s3-image"

### ISSUE THREAD

**Issue by drewbietron** [jessestuart/gatsby-source-s3-image#121]
I am trying to install the package and gatsby is having trouble loading it.  I'm getting the error, 
`Error: Unable to find plugin "gatsby-source-s3-image". Perhaps you need to install its package?`  on `[gatsby]/dist/bootstrap/load-plugins/load.js:102:11`

I have tried nuking node_modules and installing via yarn and npm and no luck.

I am on the latest version of Gatsby -> `2.0.66` and have also tried on a previous version -> `2.0.28`

Any help would be appreciated.

**Comment by pixelsonly** [comment]
@drewbietron I've found this plugin to be incompatible with Gatsby v2.x.x. I've forked this repo and it would require some work to bring up the compatibility and I haven't been able to commit to it myself. I'm not sure what @jessestuart 's future plans with this project are.

**Comment by bradpearson** [comment]
I was able to get it to work by creating an index.js file in the root of the plugin. It seems that node needs this file in order to resolve the folder as a module.

**Comment by pixelsonly** [comment]
@bradpearson that's interesting, I look forward to testing this soon on my fork.
