### ISSUE TITLE
Private S3 Bucket

### ISSUE THREAD

**Issue by johndaskovsky** [jessestuart/gatsby-source-s3-image#307]
Your documentation mentions: 

> Native integration with Gatsby's GraphQL data ontology, of course. You just provide the bucket details (and IAM credentials, if not public, which is recommended).

How are IAM credentials provided for private buckets?

**Comment by johndaskovsky** [comment]
I think I've got this one figured. Just adding the env variables when I run the gatsby develop command:
`AWS_ACCESS_KEY_ID=#### AWS_SECRET_ACCESS_KEY=#### npm run develop`

**Comment by jessestuart** [comment]
Ah, good catch — it's not super clear what's required here.

Glad you were able to figure it out! I'm updating the docs now to make this requirement more explicit.

By the way — for local development, I'd recommend logging in once through the AWS CLI (e.g., by running `aws configure`): this stores your credentials locally to `~/.aws/credentials`, and the AWS JS SDK will pick up on this automatically so you don't have to worry about managing secrets per project and whatnot. 

For CI purposes, you nailed it — just configure the environment variables somewhere they won't be publicly readable. I use this, for example, to pull from a private bucket in Netlify when building [my site](https://github.com/jessestuart/jesses.io): 
<img width="400" alt="Screenshot 2019-05-15 17 32 59" src="https://user-images.githubusercontent.com/583147/57811162-8c2a4d80-7737-11e9-8d3a-afa181ef380f.png">

**Comment by wmlutz** [comment]
So small problem here. If you're using Amplify Console (Deploy from repo) then you can have environment variables starting with "AWS".
